name: CI

on:
  push:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          path: main

      - name: Checkout dist
        uses: actions/checkout@v4
        with:
          ref: dist
          path: dist

      - name: Compile to CSS
        uses: gha-utilities/sass-build@v0.6.0
        with:
          source: main/src/DiscordMessageStyles.scss
          destination: dist/DiscordMessageStyles.css

      - name: Push dist
        run: |
          cd dist
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Compile CSS"
          git push
